num_agents: 10 #1000
num_steps: 100 #100_000
max_words: 0 #0
vocab_size: 10_000
seed: 0
deterministic: False 
groq_api: True #True
service: groq


experiments:
- name: na5e2-ns1e4
  model_parameters: 
  - model_path: "gemma2-9b-it" #"meta-llama/Llama-3.2-3B" #"llama3-70b-8192" #"mistralai/Mistral-7B-v0.1" #"llama-3.2-3b-preview" #"google-t5/t5-small"   
  - model_name: "gemma2-9b-it" #"Llama-3.2-3B" #"llama3-70b-8192" #"t5-small"
  - temperature: 
      - 0.75

      
