num_agents: 30 #150 #1000
num_steps:  50 #70_000
max_words: 0 #0
vocab_size: 10_000
deterministic: False
groq_api: False #True
service: ollama

experiments:
- name: na1p5e2-n11e4
  model_parameters: 
  - model_path: mistral:7b #gemma2:2b #mistral-small3.2:24b #phi4-mini:3.8b #llama3.1:8b 
  - model_name: mistral:7b #gemma2:2b #mistral-small3.2:24b #phi4-mini:3.8b #llama3.1:8b 
  - seed: [100, 101]
  - temperature: [0.04, 0.12] #[0.05, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 5.0] #[0.005, 0.01, 0.03, 0.1, 0.5, 1.0, 1.5, 2.0]